import puppeteer from 'puppeteer-core';
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/usr/bin/chromium', headless: 'new', args: ['--no-sandbox','--disable-dev-shm-usage','--use-gl=swiftshader','--enable-unsafe-swiftshader','--window-size=1600,900'] });
const page = await browser.newPage();
await page.setViewport({ width: 1600, height: 900 });
await page.goto('http://localhost:5188/', { waitUntil: 'domcontentloaded' });
await sleep(2200);
await page.click('#btnNew');
await sleep(700);
await page.evaluate(() => { window.__game.spawnMob('biber'); window.__game.spawnMob('clog'); window.__game.spawnMob('biber'); window.__game.spawnMob('biber'); });
await sleep(1600);
await page.screenshot({ path: 'shot-combat.png' });
await page.evaluate(() => { window.__game.startBoss(); });
await sleep(2600);
await page.evaluate(() => { window.__game.nearBoss(); });
await sleep(1200);
await page.screenshot({ path: 'shot-boss.png' });
console.log('shots done');
await browser.close();
